version: '3'

services: 
  goapp: 
    build: .
    ports:
     - 3000:3000
    volumes: 
      - .:/app/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
#    volumes: 
#      - .:/app/volumes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_ROOT: root

      #SQL
#create table datapix (id varchar(255), id_pay bigint, created_at varchar(40), expires_at varchar(40), status varchar(30), type varchar(30), amount float, ticket varchar(50), qrcode varchar(255), qrcodebase longtext);